const wilayaOptions = [
    { value: 'Alger', label: 'Alger' },
    { value: 'Adrar', label: 'Adrar' },
    { value: 'Chlef', label: 'Chlef' },
    // { value: 'Laghouat', label: 'Laghouat' },
    // { value: 'Oum El Bouaghi', label: 'Oum El Bouaghi' },
    // { value: 'Batna', label: 'Batna' },
    // { value: 'Bejaia', label: 'Bejaia' },
    // { value: 'Biskra', label: 'Biskra' },
    // { value: 'Bechar', label: 'Bechar' },
    // { value: 'Blida', label: 'Blida' },
    // { value: 'Bouira', label: 'Bouira' },
    // { value: 'Tamanrasset', label: 'Tamanrasset' },
    // { value: 'Tebessa', label: 'Tebessa' },
    // { value: 'Tlemcen', label: 'Tlemcen' },
    // { value: 'Tiaret', label: 'Tiaret' },
    // { value: 'Tizi Ouzou', label: 'Tizi Ouzou' },
    // { value: 'Algiers', label: 'Algiers' },
    // { value: 'Djelfa', label: 'Djelfa' },
    // { value: 'Jijel', label: 'Jijel' },
    // { value: 'Setif', label: 'Setif' },
    // { value: 'Saida', label: 'Saida' },
    // { value: 'Skikda', label: 'Skikda' },
    // { value: 'Sidi Bel Abbes', label: 'Sidi Bel Abbes' },
    // { value: 'Annaba', label: 'Annaba' },
    // { value: 'Guelma', label: 'Guelma' },
    // { value: 'Constantine', label: 'Constantine' },
    // { value: 'Medea', label: 'Medea' },
    // { value: 'Mostaganem', label: 'Mostaganem' },
    // { value: 'Msila', label: 'Msila' },
    // { value: 'Mascara', label: 'Mascara' },
    // { value: 'Ouargla', label: 'Ouargla' },
    // { value: 'Oran', label: 'Oran' },
    // { value: 'El Bayadh', label: 'El Bayadh' },
    // { value: 'Illizi', label: 'Illizi' },
    // { value: 'Bordj Bou Arreridj', label: 'Bordj Bou Arreridj' },
    // { value: 'Boumerdes', label: 'Boumerdes' },
    // { value: 'El Tarf', label: 'El Tarf' },
    // { value: 'Tindouf', label: 'Tindouf' },
    // { value: 'Tissemsilt', label: 'Tissemsilt' },
    // { value: 'El Oued', label: 'El Oued' },
    // { value: 'Khenchela', label: 'Khenchela' },
    // { value: 'Souk Ahras', label: 'Souk Ahras' },
    // { value: 'Tipaza', label: 'Tipaza' },
    // { value: 'Mila', label: 'Mila' },
    // { value: 'Aïn Defla', label: 'Aïn Defla' },
    // { value: 'Naama', label: 'Naama' },
    // { value: 'Aïn Temouchent', label: 'Aïn Temouchent' },
    // { value: 'Ghardaia', label: 'Ghardaia' },
    // { value: 'Relizane', label: 'Relizane' },
    // { value: 'Timimoun', label: 'Timimoun' },
    // { value: 'Bordj Badji Mokhtar', label: 'Bordj Badji Mokhtar' },
    // { value: 'Ouled Djellal', label: 'Ouled Djellal' },
    // { value: 'Béni Abbès', label: 'Béni Abbès' },
    // { value: 'In Salah', label: 'In Salah' },
    // { value: 'In Guezzam', label: 'In Guezzam' },
    // { value: 'Touggourt', label: 'Touggourt' },
    // { value: 'Djanet', label: 'Djanet' },
    // { value: 'El MGhaier', label: 'El MGhaier' },
    // { value: 'El Meniaa', label: 'El Meniaa' }
  ];
  
export default wilayaOptions;
  